---
- name: Install git on all servers
  hosts: all
  tasks:
    - name: Install git on Ubuntu servers
      apt:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Install git on Redhat servers
      yum:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
